## Data Analytics

### Numpy

In [1]:
import numpy as np

In [3]:
n = np.array([])

In [4]:
n

array([], dtype=float64)

In [5]:
print(n)

[]


In [7]:
n.shape

(0,)

In [8]:
n.size

0

In [10]:
len(n)

0

In [11]:
n.dtype

dtype('float64')

In [30]:
n = np.array([2,3,4,5,6])

In [13]:
n.dtype

dtype('int32')

In [15]:
mp = np.array([[2,3,4],[1,2,3]])

In [17]:
mp.shape

(2, 3)

In [18]:
mp

array([[2, 3, 4],
       [1, 2, 3]])

In [19]:
np1 = np.array([[1,2,3],[1,2,3],[1,2,4],[2,3,4]]) #row - [ column ] 

In [20]:
np1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 4],
       [2, 3, 4]])

In [21]:
len(np1)

4

In [22]:
np1.shape

(4, 3)

## For 3D matrix

In [24]:
#accessing the elements

In [25]:
np3 = np.array([[[8,81],[7,71],[6,61]],[[9,91],[4,41],[18,181]]])

In [27]:
np3.shape # 2 rows, 3 columns, 2 rows

(2, 3, 2)

In [28]:
np3[:,1,:]

array([[ 7, 71],
       [ 4, 41]])

In [29]:
np3[1]

array([[  9,  91],
       [  4,  41],
       [ 18, 181]])

## modifying

In [31]:
n = np.array([2,3,4,5,6])

In [32]:
n[0] = 20

In [33]:
n

array([20,  3,  4,  5,  6])

In [34]:
## array creating functions

In [35]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [38]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
np.arange(1,100,5) # 1 se 100 tak 5 ke difference me

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [42]:
np.linspace(1,100,20) #1 se 100 tak 20 values

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [44]:
np.eye(3)     #creating identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.random.rand(3,4)*20

array([[ 5.55905484,  0.42717688,  0.65743619,  2.35276458],
       [10.11267964,  7.89593475,  7.29305322, 15.81031199],
       [ 0.27230862, 16.88608279,  3.26576341, 14.09043951]])

In [55]:
k = np.random.randint(1,100,(2,3)) #1 se 100 tak - 2 row 3column ka matrix


## working with matrix - operations

In [54]:
## statistic functions

In [56]:
k

array([[95, 30, 54],
       [63, 74, 29]])

In [58]:
k.sum()

345

In [59]:
k.min()

29

In [60]:
k.max()

95

In [61]:
k.sum(axis=1)

array([179, 166])

### <b>we are saving a variable</b>

In [62]:
k

array([[95, 30, 54],
       [63, 74, 29]])

In [64]:
np.save('my_array',k) # this is <jis_naam se save hoga>,<jisko save krna hai>

In [65]:
#loading the file

In [66]:
obj = np.load('my_array.npy')