In [8]:
import numpy as np

In [9]:
np1 = np.array([1,2,3,4])

In [10]:
np1

array([1, 2, 3, 4])

In [11]:
type(np1)

numpy.ndarray

In [12]:
np2 = np.array(['str','this','is'])

In [13]:
np2

array(['str', 'this', 'is'], dtype='<U4')

In [18]:
np3 = np.array([[2,3,5,5],[1,2,3,4.0]])

In [19]:
print(np3)

[[2. 3. 5. 5.]
 [1. 2. 3. 4.]]


In [20]:
np3 = np.zeros(3)

In [21]:
np3

array([0., 0., 0.])

In [38]:
np3 = np.ones((2,3),dtype=int)

In [39]:
np3

array([[1, 1, 1],
       [1, 1, 1]])

In [33]:
np3 = np.eye(4, dtype=int)
np3

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [36]:
np3.ndim #dimension of array

2

In [40]:
np3.shape

(2, 3)

In [42]:
len(np3)#this gives number of rows

2

In [47]:
print(np3.max())


1


In [52]:
print(np3.mean())

1.0


In [58]:
np3 = np.random.rand(3,2)    #this gives a random number is the given shape between 1 and 0

In [59]:
np3

array([[0.0522916 , 0.94150196],
       [0.66808604, 0.55814327],
       [0.84574698, 0.54354353]])

In [65]:
np3 = np.random.randint(1,100,(2,3))

In [66]:
np3

array([[83, 19, 38],
       [17, 29, 23]])

In [67]:
np3.dtype

dtype('int32')

In [68]:
np3

array([[83, 19, 38],
       [17, 29, 23]])

In [69]:
np3.itemsize

4

In [71]:
np3.size#this is no of elements

6

np3*np1

## <b>Updating and Accessing Elements</b>

In [76]:
a = np.random.randint(1,50,(4,5))

In [77]:
a

array([[ 5, 22, 49,  9,  9],
       [44, 13, 40, 22, 28],
       [13, 10, 40, 44, 38],
       [11, 32, 14, 38,  9]])

In [78]:
#<name>[row,column,layer]

In [79]:
a[1,2]

40

In [80]:
a[:3,:3]

array([[ 5, 22, 49],
       [44, 13, 40],
       [13, 10, 40]])

In [91]:
a

array([[ 5, 22, 49,  9,  9],
       [44, 13, 40, 22, 28],
       [13, 10, 40, 44, 38],
       [11, 32, 14, 38,  9]])

In [82]:
a[0,:]

array([ 5, 22, 49,  9,  9])

In [83]:
a[:,0]

array([ 5, 44, 13, 11])

## Initializing the matrix

In [90]:
#this also takes shapes and fill with what we want
np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

In [86]:
np.full((2,5),"str")

array([['str', 'str', 'str', 'str', 'str'],
       ['str', 'str', 'str', 'str', 'str']], dtype='<U3')

In [93]:
#creating full using some other shape
np.full_like(a,3)   #shape of "a" with all 3's

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [92]:
#creating with random numbers with someone elese shape
np.random.random_sample(a.shape)

array([[0.47840896, 0.12976016, 0.01444298, 0.10306202, 0.21723396],
       [0.21644213, 0.21424692, 0.78531527, 0.03995401, 0.55170643],
       [0.48926404, 0.29944204, 0.23168747, 0.40265624, 0.60831711],
       [0.64596628, 0.51645594, 0.88278995, 0.36001711, 0.17199699]])

#### <b>Net wala question</b>

In [98]:
output = np.ones((5,5),dtype=int)
output

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [100]:
output[1:4,1:4] = np.zeros((3,3))

In [101]:
output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [102]:
output[2,2] = 9

In [103]:
output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

## Maths on numpy

In [104]:
a


array([[ 5, 22, 49,  9,  9],
       [44, 13, 40, 22, 28],
       [13, 10, 40, 44, 38],
       [11, 32, 14, 38,  9]])

In [105]:
a + 2

array([[ 7, 24, 51, 11, 11],
       [46, 15, 42, 24, 30],
       [15, 12, 42, 46, 40],
       [13, 34, 16, 40, 11]])

In [106]:
a*2

array([[10, 44, 98, 18, 18],
       [88, 26, 80, 44, 56],
       [26, 20, 80, 88, 76],
       [22, 64, 28, 76, 18]])

In [108]:
b = np.full((5,1),5)

##### linear algebra

In [112]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [116]:
b = np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [118]:
#this is used for multiplying two matrices
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [119]:
#finding out determinant
np.linalg.det(np.matmul(a,b))

0.0

In [120]:
np.linalg.matrix_rank(a)

1

#### <b>formaing 3D array></b>

In [2]:
import numpy as np

In [3]:
a = np.array([[[1,3],[2,6],[3,7]],[[2,4],[3,5],[4,6]],[[2,6],[3,7],[4,6]]])

In [4]:
a.shape

(3, 3, 2)

In [5]:
a.size

18

In [13]:
d = a.max()

In [14]:
d

7

In [17]:
test = np.random.randint(1,20,(3,3))

In [18]:
test

array([[10,  8, 12],
       [13, 14, 14],
       [ 1,  9, 10]])

In [19]:
np.linalg.det(test)

447.9999999999999

In [21]:
test[1:,1:] = np.full((2,2),0)

In [22]:
test

array([[10,  8, 12],
       [13,  0,  0],
       [ 1,  0,  0]])